"""Added date_added to user

Revision ID: 3db6e2257fbc
Revises: e1ff4f84f23a
Create Date: 2026-05-06 20:34:22.071206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db6e2257fbc'
down_revision = 'e1ff4f84f23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
