"""added file_url to assignment

Revision ID: 954f30bbf514
Revises: 8ab305be8e9b
Create Date: 2026-04-17 13:38:51.959236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954f30bbf514'
down_revision = '8ab305be8e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
