"""add answers column

Revision ID: c51bfb4ce7bd
Revises: dc7089583933
Create Date: 2026-04-17 19:45:33.796571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51bfb4ce7bd'
down_revision = 'dc7089583933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_column('answers')

    # ### end Alembic commands ###
