"""Added profile fields to user model

Revision ID: e1ff4f84f23a
Revises: c51bfb4ce7bd
Create Date: 2026-05-06 20:04:46.109429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ff4f84f23a'
down_revision = 'c51bfb4ce7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('enrollment_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('class_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('section', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_users_employee_id', ['employee_id'])
        batch_op.create_unique_constraint('uq_users_enrollment_no', ['enrollment_no'])
        batch_op.create_unique_constraint('uq_users_student_id', ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('department')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('section')
        batch_op.drop_column('class_name')
        batch_op.drop_column('course')
        batch_op.drop_column('enrollment_no')
        batch_op.drop_column('student_id')
        batch_op.drop_column('phone')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
