"""Added permission flags

Revision ID: ff23515c4e03
Revises: 263a118d05f6
Create Date: 2026-02-28 16:11:12.540600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff23515c4e03'
down_revision = '263a118d05f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_access_teacher', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_access_student', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_access_student')
        batch_op.drop_column('can_access_teacher')

    # ### end Alembic commands ###
